const types = {
    FETCH_PLAYERS:"FETCH_PLAYERS",
    FETCH_MATCHES:"FETCH_MATCHES",
    NEW_MATCH:"NEW_MATCH",
    LOGIN_CHECK:"LOGIN_CHECK",
    LOGOUT:"LOGOUT",
    SET_APP_STATUS_OFFLINE:"SET_APP_STATUS_OFFLINE",
    SET_APP_STATUS_LOADING:"SET_APP_STATUS_LOADING",
    LOGIN:"LOGIN",
    NEW_PLAYER:"NEW_PLAYER",
    EDIT_PLAYER:"EDIT_PLAYER",
    DELETE_PLAYER:"DELETE_PLAYER"

}
export default types